# Generated by Django 5.1.1 on 2024-10-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_teacher',
            name='Class',
            field=models.CharField(blank=True, choices=[('12', '12'), ('9', '9')], default='12', max_length=15),
        ),
    ]
