# Generated by Django 5.1.1 on 2024-10-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_teacher_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_teacher',
            name='Class',
            field=models.CharField(blank=True, choices=[('12', 'بكلوريا'), ('9', 'تاسع'), ('9_12', ' تاسع و بكلوريا')], default='12', max_length=15),
        ),
    ]
