# Generated by Django 5.1.1 on 2024-10-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_teacher_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_teacher',
            name='studying_subjects',
            field=models.CharField(choices=[('all', 'عرض الكل'), ('math', 'رياضيات'), ('physics', 'فيزياء'), ('chemistry', 'كيمياء'), ('science', 'علوم'), ('arabic', 'عربي'), ('english', 'إنكليزي'), ('france', 'فرنسي'), ('national', 'وطنية'), ('islam', 'ديانة'), ('physics_chemistry', 'فيزياء و كيمياء'), ('geography', 'اجتماعيات')], max_length=100),
        ),
    ]
