# Generated by Django 5.1.1 on 2024-10-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_teacher_studying_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_teacher',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
