# Generated by Django 5.1.1 on 2024-10-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_teacher_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_teacher',
            name='number_of_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
