# Generated by Django 5.1.1 on 2024-10-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_teacher_number_of_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_teacher',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
