# Generated by Django 5.1.1 on 2024-12-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_teacher_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_teacher',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='facebook_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='instagram_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='teaching_in_institutions',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='teaching_in_school',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='telegram_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
