# Generated by Django 5.1.1 on 2024-12-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_profile_teacher_bio_profile_teacher_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_student',
            name='school',
            field=models.CharField(blank=True, default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile_teacher',
            name='studying_subjects',
            field=models.CharField(choices=[('math', 'رياضيات'), ('physics', 'فيزياء'), ('chemistry', 'كيمياء'), ('science', 'علوم'), ('arabic', 'عربي'), ('english', 'إنكليزي'), ('france', 'فرنسي'), ('islam', 'ديانة'), ('physics_chemistry', 'فيزياء و كيمياء'), ('geography', 'اجتماعيات')], max_length=100),
        ),
    ]
