# Generated by Django 5.1.1 on 2024-12-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_student_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_student',
            name='phone_number',
            field=models.CharField(blank=True, default='-', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile_teacher',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='profile_teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='TeachersImages/', verbose_name='إضافة صورة'),
        ),
    ]
