# Generated by Django 5.1.1 on 2024-12-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_student_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_student',
            name='Class',
            field=models.CharField(blank=True, default='12', max_length=2),
        ),
    ]
