# Generated by Django 5.1.1 on 2024-12-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_profile_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_student',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
