# Generated by Django 5.1.1 on 2024-12-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_profile_student_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_student',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
