# Generated by Django 5.1.1 on 2025-01-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_teacher',
            name='number_of_exams',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='number_of_notes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
