# Generated by Django 5.1.1 on 2025-02-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_profile_teacher_number_of_exams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='StudentsImages/', verbose_name='إضافة صورة'),
        ),
    ]
