# Generated by Django 5.1.1 on 2025-03-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_profile_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile_student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile_teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile_teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='profile_student',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AddField(
            model_name='profile_teacher',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
    ]
