# Generated by Django 5.1.1 on 2025-08-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_remove_profile_student_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_teacher',
            name='number_of_likes',
        ),
    ]
