# Generated by Django 5.2.5 on 2025-08-25 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_remove_profile_teacher_number_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile_student',
            name='image',
        ),
    ]
