# Generated by Django 5.2.5 on 2025-08-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_profile_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_teacher',
            name='Class',
            field=models.CharField(blank=True, choices=[('12', 'بكلوريا'), ('9', 'تاسع'), ('9_12', 'تاسع و بكلوريا')], default='12', max_length=15),
        ),
    ]
