# Generated by Django 5.1.1 on 2024-10-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('test_packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_content', models.TextField()),
                ('option_A', models.TextField(blank=True, null=True)),
                ('option_B', models.TextField(blank=True, null=True)),
                ('option_C', models.TextField(blank=True, null=True)),
                ('option_D', models.TextField(blank=True, null=True)),
                ('option_E', models.TextField(blank=True, null=True)),
                ('right_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], default='A', max_length=1)),
                ('explanation', models.TextField(default='لا يتوفر شرح للإجابة', help_text='شرح الإجابة الصحيحة')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_packages.testpackage')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(blank=True, choices=[('test_content', ' test_content'), ('option_A', ' option_A'), ('option_B', 'option_B'), ('option_C', 'option_C'), ('option_D', 'option_D'), ('option_E', 'option_E'), ('explanation', 'explanation')], default='test_content', max_length=100)),
                ('images', models.ImageField(blank=True, null=True, upload_to='ImagesForTests/', verbose_name='إضافة صورة')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questions')),
            ],
        ),
    ]
