# Generated by Django 5.1.1 on 2025-01-25 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('test_packages', '0006_testpackage_number_of_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionimages',
            name='package',
            field=models.ForeignKey(default=15, on_delete=django.db.models.deletion.CASCADE, to='test_packages.testpackage'),
        ),
    ]
