# Generated by Django 5.1.1 on 2025-01-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_questionimages_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionimages',
            name='package',
        ),
    ]
