# Generated by Django 5.1.1 on 2025-01-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_questionimages_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimages',
            name='field_name',
            field=models.CharField(blank=True, choices=[('test_content', ' test_content'), ('option_A', ' option_A'), ('option_B', 'option_B'), ('option_C', 'option_C'), ('option_D', 'option_D'), ('option_E', 'option_E'), ('explanation', 'explanation')], default='test_content', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='explanation',
            field=models.TextField(blank=True, default='لا يتوفر شرح للإجابة', help_text='شرح الإجابة الصحيحة', null=True),
        ),
    ]
