# Generated by Django 5.1.1 on 2025-01-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questionimages_field_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='ImagesForQuestions/', verbose_name='إضافة صورة'),
        ),
    ]
