# Generated by Django 5.1.1 on 2025-02-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_questionimages_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='right_answer',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
