# Generated by Django 5.1.1 on 2025-02-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_questions_right_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='right_answer',
            field=models.CharField(default='A', max_length=5),
        ),
    ]
