# Generated by Django 5.2.5 on 2025-08-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_questions_right_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionimages',
            name='field_name',
            field=models.CharField(blank=True, choices=[('test_content', 'test_content'), ('option_A', 'option_A'), ('option_B', 'option_B'), ('option_C', 'option_C'), ('option_D', 'option_D'), ('option_E', 'option_E'), ('explanation', 'explanation')], default='test_content', max_length=100, null=True),
        ),
    ]
