# Generated by Django 5.1.1 on 2025-08-09 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0012_alter_notes_subject_name'),
        ('profiles', '0018_remove_profile_teacher_number_of_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReadNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(help_text='Name of the subject associated with the note', max_length=25, verbose_name='Subject Name')),
                ('note_name', models.CharField(help_text='Title or name of the note', max_length=2000, verbose_name='Note Name')),
                ('publisher_id', models.BigIntegerField(help_text='ID of the note publisher', verbose_name='Publisher ID')),
                ('publisher_name', models.CharField(help_text='Name of the note publisher', max_length=127, verbose_name='Publisher Name')),
                ('number_of_reads', models.IntegerField(default=1, help_text='Number of times this note has been read by this student', verbose_name='Number of Reads')),
                ('first_read_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the student first read this note', verbose_name='First Read At')),
                ('last_read_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when the student last read this note', verbose_name='Last Read At')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_reads', to='notes.notes', verbose_name='Note')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_notes', to='profiles.profile_student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Read Note',
                'verbose_name_plural': 'Student Read Notes',
                'ordering': ['-last_read_at'],
                'unique_together': {('student', 'note_id')},
            },
        ),
    ]
