# Generated by Django 5.2.5 on 2025-08-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentReadNotes', '0001_initial'),
        ('notes', '0013_alter_notes_options'),
        ('profiles', '0020_alter_profile_teacher_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreadnotes',
            name='note_id',
            field=models.ForeignKey(help_text='Reference to the note that was read', on_delete=django.db.models.deletion.CASCADE, related_name='student_reads', to='notes.notes', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='studentreadnotes',
            name='student',
            field=models.ForeignKey(help_text='Reference to the student who read this note', on_delete=django.db.models.deletion.CASCADE, related_name='read_notes', to='profiles.profile_student', verbose_name='Student'),
        ),
    ]
