# Generated by Django 5.1.1 on 2024-10-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(help_text=' هون منحط شو محتوى الاختبار , متل مثلا اختبار في وحدة الأعصاب , وفي وحدة الهرمونات أو شامل', max_length=500)),
                ('publisher_name', models.CharField(blank=True, default='SVI', max_length=255)),
                ('units', models.CharField(help_text='هون منحط الوحدات بالاسم يلي الاختبار عم يحكي عنهم , اذا في اكتر من وحدة افصل بينهم بفاصلةعادية  ', max_length=800)),
                ('subject_name', models.CharField(blank=True, choices=[('math_12', ' رياضيات بكلوريا'), ('science_12', ' علوم بكلوريا'), ('english_12', 'انكليزي بكلوريا'), ('arabic_12', 'عربي بكلوريا'), ('physics_12', 'فيزياء بكلوريا'), ('chemistry_12', 'كيمياء بكلوريا'), ('national_12', ' وطنية بكلوريا'), ('france_12', 'فرنسي بكلوريا'), ('math_9', 'رياضيات تاسع'), ('science_9', 'علوم تاسع'), ('english_9', 'انكليزي تاسع'), ('arabic_9', 'عربي تاسع'), ('physics_chemistry_9', 'فيزياء و كيمياء تاسع'), ('geography_9', 'اجتماعيات تاسع'), ('france_9', 'فرنسي تاسع')], default='math_12', max_length=25)),
                ('premium', models.BooleanField(blank=True, default=False)),
                ('price', models.IntegerField(blank=True, default=0)),
                ('number_of_apps', models.IntegerField(default=0, editable=False, verbose_name='number of applications')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
