# Generated by Django 5.1.1 on 2024-10-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpackage',
            name='publisher_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
