# Generated by Django 5.1.1 on 2024-12-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0002_testpackage_publisher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpackage',
            name='Class',
            field=models.CharField(default='12', max_length=2),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='subject_name',
            field=models.CharField(blank=True, choices=[('math', ' رياضيات  '), ('science ', ' علوم  '), ('english', 'انكليزي  '), ('arabic', 'عربي  '), ('physics', 'فيزياء  '), ('chemistry', 'كيمياء  '), ('physics_chemistry ', 'فيزياء و كيمياء '), ('islam', 'الديانة الإسلامية'), ('france', 'فرنسي  '), ('geography', 'اجتماعيات ')], default='math', max_length=25),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='units',
            field=models.CharField(max_length=1000),
        ),
    ]
