# Generated by Django 5.1.1 on 2025-01-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0005_remove_testpackage_publisher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpackage',
            name='number_of_questions',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
