# Generated by Django 5.1.1 on 2025-01-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0006_testpackage_number_of_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpackage',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
