# Generated by Django 5.1.1 on 2025-01-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0007_alter_testpackage_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpackage',
            name='number_of_apps',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='number of applications'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
