# Generated by Django 5.1.1 on 2025-02-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0008_alter_testpackage_number_of_apps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpackage',
            name='number_of_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
