# Generated by Django 5.1.1 on 2025-03-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0009_testpackage_number_of_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpackage',
            name='publisher_name',
            field=models.CharField(blank=True, default='SVI', max_length=127),
        ),
    ]
