# Generated by Django 5.1.1 on 2025-03-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0010_testpackage_publisher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpackage',
            name='premium',
        ),
    ]
