# Generated by Django 5.1.1 on 2025-08-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0011_remove_testpackage_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testpackage',
            name='subject_name',
            field=models.CharField(blank=True, default='math_12', max_length=25),
        ),
    ]
