# Generated by Django 5.2.5 on 2025-08-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0012_alter_testpackage_subject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testpackage',
            options={'ordering': ['-date_added']},
        ),
    ]
