# Generated by Django 5.2.5 on 2025-08-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_packages', '0013_alter_testpackage_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpackage',
            name='number_of_comments',
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='Class',
            field=models.CharField(default='12', help_text='Class/grade level for this test package', max_length=2),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='date_added',
            field=models.DateField(auto_now_add=True, help_text='Date when the package was added to the system'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='number_of_apps',
            field=models.IntegerField(blank=True, default=0, editable=False, help_text='Number of times this package has been accessed', verbose_name='number of applications'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='number_of_purchases',
            field=models.IntegerField(default=0, editable=False, help_text='Number of times this package has been purchased'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='number_of_questions',
            field=models.IntegerField(blank=True, default=0, help_text='Total number of questions in this test package'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='package_name',
            field=models.CharField(help_text='هون منحط شو محتوى الاختبار , متل مثلا اختبار في وحدة الأعصاب , وفي وحدة الهرمونات أو شامل', max_length=500),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='price',
            field=models.IntegerField(blank=True, default=0, help_text='Price of the test package in currency units'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='publisher_id',
            field=models.BigIntegerField(default=1, help_text='ID of the teacher who published this test package'),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='publisher_name',
            field=models.CharField(blank=True, default='SVI', help_text='Name of the teacher who published this package', max_length=127),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='subject_name',
            field=models.CharField(blank=True, default='math_12', help_text='Subject name for this test package', max_length=25),
        ),
        migrations.AlterField(
            model_name='testpackage',
            name='units',
            field=models.CharField(help_text='Units or topics covered in this test package', max_length=1000),
        ),
    ]
