# Generated by Django 5.1.1 on 2025-08-09 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0012_alter_notes_subject_name'),
        ('profiles', '0018_remove_profile_teacher_number_of_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPremiumContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(help_text='Name of the class associated with the premium content', max_length=25, verbose_name='Class Name')),
                ('type', models.CharField(help_text='Type of the premium content', max_length=25, verbose_name='Type')),
                ('subject_name', models.CharField(help_text='Name of the subject associated with the premium content', max_length=25, verbose_name='Subject Name')),
                ('content_name', models.CharField(help_text='Title or name of the content', max_length=2000, verbose_name='Content Name')),
                ('publisher_id', models.BigIntegerField(help_text='ID of the note publisher', verbose_name='Publisher ID')),
                ('publisher_name', models.CharField(help_text='Name of the note publisher', max_length=127, verbose_name='Publisher Name')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the student purchased the premium content', verbose_name='Purchase Date')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the premium content', max_digits=10, verbose_name='Price')),
                ('date_of_expiry', models.DateTimeField(help_text='Date of expiry of the premium content', verbose_name='Date of Expiry')),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_premium_content', to='notes.notes', verbose_name='Content')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_content', to='profiles.profile_student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Student Premium Content',
                'verbose_name_plural': 'Student Premium Content',
                'ordering': ['-purchase_date'],
                'unique_together': {('student', 'content_id')},
            },
        ),
    ]
