# Generated by Django 5.1.1 on 2025-08-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPremiumContent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentpremiumcontent',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Whether the premium content is expired', verbose_name='Is Expired'),
        ),
    ]
