# Generated by Django 5.1.1 on 2025-08-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPremiumContent', '0002_studentpremiumcontent_is_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpremiumcontent',
            name='date_of_expiry',
            field=models.DateField(help_text='Date of expiry of the premium content', verbose_name='Date of Expiry'),
        ),
        migrations.AlterField(
            model_name='studentpremiumcontent',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, help_text='Timestamp of when the student purchased the premium content', verbose_name='Purchase Date'),
        ),
    ]
