# Generated by Django 5.1.1 on 2025-08-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPremiumContent', '0003_alter_studentpremiumcontent_date_of_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpremiumcontent',
            name='content_id',
            field=models.IntegerField(help_text='ID of the content', verbose_name='Content ID'),
        ),
    ]
