# Generated by Django 5.1.1 on 2025-08-09 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPremiumContent', '0004_alter_studentpremiumcontent_content_id'),
        ('profiles', '0018_remove_profile_teacher_number_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpremiumcontent',
            name='content_id',
            field=models.BigIntegerField(help_text='ID of the content', verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='studentpremiumcontent',
            name='publisher_id',
            field=models.ForeignKey(help_text='ID of the note publisher', on_delete=django.db.models.deletion.DO_NOTHING, to='profiles.profile_teacher', verbose_name='Publisher ID'),
        ),
    ]
