# Generated by Django 5.1.1 on 2025-08-09 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPremiumContent', '0005_alter_studentpremiumcontent_content_id_and_more'),
        ('profiles', '0018_remove_profile_teacher_number_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpremiumcontent',
            name='Class',
            field=models.CharField(help_text='Name of the class associated with the premium content', max_length=25, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='studentpremiumcontent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='premium_content', to='profiles.profile_student', verbose_name='Student'),
        ),
    ]
