# Generated by Django 5.2.5 on 2025-08-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentPremiumContent', '0006_alter_studentpremiumcontent_class_and_more'),
        ('profiles', '0019_remove_profile_student_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentpremiumcontent',
            unique_together={('student', 'content_id', 'type')},
        ),
        migrations.AddField(
            model_name='studentpremiumcontent',
            name='student_name',
            field=models.CharField(default='', help_text='Name of the student who purchased the premium content', max_length=256, verbose_name='Student Name'),
        ),
    ]
