# Generated by Django 5.1.1 on 2024-10-05 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('publisher_name', models.CharField(blank=True, default='SVI', max_length=255)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('premium', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='noteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='ImagesForTests/', verbose_name='إضافة صورة')),
                ('note_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notes')),
            ],
        ),
    ]
