# Generated by Django 5.1.1 on 2024-10-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='number_of_reads',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='number of reads'),
        ),
    ]
