# Generated by Django 5.1.1 on 2024-10-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_number_of_reads'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='publisher_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
