# Generated by Django 5.1.1 on 2024-12-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_publisher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='Class',
            field=models.CharField(blank=True, default='12', max_length=25),
        ),
        migrations.AlterField(
            model_name='notes',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notes',
            name='publisher_id',
            field=models.BigIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject_name',
            field=models.CharField(blank=True, choices=[('math', ' رياضيات  '), ('science ', ' علوم  '), ('english', 'انكليزي  '), ('arabic', 'عربي  '), ('physics', 'فيزياء  '), ('chemistry', 'كيمياء  '), ('physics_chemistry ', 'فيزياء و كيمياء '), ('islam', 'الديانة الإسلامية'), ('france', 'فرنسي  '), ('geography', 'اجتماعيات ')], default='math', max_length=25),
        ),
    ]
