# Generated by Django 5.1.1 on 2024-12-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_notes_class_alter_notes_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='number_of_purchases',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject_name',
            field=models.CharField(blank=True, choices=[('math', ' رياضيات  '), ('science', ' علوم  '), ('english', 'انكليزي  '), ('arabic', 'عربي  '), ('physics', 'فيزياء  '), ('chemistry', 'كيمياء  '), ('physics_chemistry', 'فيزياء و كيمياء '), ('islam', 'الديانة الإسلامية'), ('france', 'فرنسي  '), ('geography', 'اجتماعيات ')], default='math', max_length=25),
        ),
    ]
