# Generated by Django 5.1.1 on 2024-12-26 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_notes_number_of_purchases_alter_notes_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='publisher_name',
        ),
    ]
