# Generated by Django 5.1.1 on 2025-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_remove_notes_publisher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noteimages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='ImagesForNotes/', verbose_name='إضافة صورة'),
        ),
    ]
