# Generated by Django 5.1.1 on 2025-02-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_alter_noteimages_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='number_of_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
