# Generated by Django 5.1.1 on 2025-03-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_notes_publisher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='premium',
        ),
    ]
