# Generated by Django 5.1.1 on 2025-08-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_remove_notes_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='subject_name',
            field=models.CharField(blank=True, default='math_12', max_length=25),
        ),
    ]
