# Generated by Django 5.2.5 on 2025-08-25 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_notes_subject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-date_uploaded']},
        ),
    ]
