# Generated by Django 5.2.5 on 2025-08-25 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class', models.CharField(default='12', max_length=2, verbose_name='Class')),
                ('subject_name', models.CharField(max_length=25, verbose_name='Subject Name')),
                ('number_of_notes', models.IntegerField(default=0, verbose_name='Number of Notes')),
                ('number_of_exams', models.IntegerField(default=0, verbose_name='Number of Exams')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_tracking', to=settings.AUTH_USER_MODEL, verbose_name='Student ID (FK)')),
            ],
            options={
                'verbose_name': 'Student Subject Tracking',
                'verbose_name_plural': 'Student Subject Tracking',
                'ordering': ['-id'],
                'unique_together': {('student', 'subject_name', 'Class')},
            },
        ),
    ]
