# Generated by Django 5.2.5 on 2025-08-30 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentSubjectTracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubjecttracking',
            name='Class',
            field=models.CharField(default='12', help_text="Class (e.g., '9', '12', '9_12')", max_length=2, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='studentsubjecttracking',
            name='number_of_exams',
            field=models.IntegerField(default=0, help_text='Total number of exams completed by the student for this subject', verbose_name='Number of Exams'),
        ),
        migrations.AlterField(
            model_name='studentsubjecttracking',
            name='number_of_notes',
            field=models.IntegerField(default=0, help_text='Total number of notes completed by the student for this subject', verbose_name='Number of Notes'),
        ),
        migrations.AlterField(
            model_name='studentsubjecttracking',
            name='student',
            field=models.ForeignKey(help_text='Reference to the student user who is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='subject_tracking', to=settings.AUTH_USER_MODEL, verbose_name='Student ID (FK)'),
        ),
        migrations.AlterField(
            model_name='studentsubjecttracking',
            name='subject_name',
            field=models.CharField(help_text="Name of the subject being tracked (e.g., 'math', 'physics', 'chemistry')", max_length=25, verbose_name='Subject Name'),
        ),
    ]
