# Generated by Django 5.1.1 on 2024-09-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoneExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=25)),
                ('exam_name', models.CharField(max_length=50)),
                ('exam_id', models.CharField(max_length=10)),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('result', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='PremiumExams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=10)),
                ('date_of_expiration', models.DateField()),
                ('subject_name', models.CharField(max_length=25)),
                ('exam_name', models.CharField(max_length=50)),
            ],
        ),
    ]
