# Generated by Django 5.1.1 on 2024-09-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('student_related_exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneexams',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile_student'),
        ),
        migrations.AddField(
            model_name='premiumexams',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile_student'),
        ),
    ]
