# Generated by Django 5.1.1 on 2024-12-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_related_exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneexams',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doneexams',
            name='time_taken',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='exam_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='exam_name',
            field=models.CharField(max_length=100),
        ),
    ]
