# Generated by Django 5.1.1 on 2024-12-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_related_exams', '0003_doneexams_price_doneexams_time_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneexams',
            name='publisher_id',
            field=models.IntegerField(default=1),
        ),
    ]
