# Generated by Django 5.1.1 on 2024-12-29 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_profile_student_gender'),
        ('student_related_exams', '0004_doneexams_publisher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('exam', 'exam'), ('note', 'note')], max_length=5)),
                ('content_id', models.IntegerField(default=1)),
                ('date_of_expiration', models.DateField()),
                ('subject_name', models.CharField(max_length=25)),
                ('content_name', models.CharField(max_length=70)),
                ('price', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile_student')),
            ],
        ),
        migrations.DeleteModel(
            name='PremiumExams',
        ),
    ]
