# Generated by Django 5.1.1 on 2024-12-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_related_exams', '0005_premiumcontent_delete_premiumexams'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcontent',
            name='publisher_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='premiumcontent',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
