# Generated by Django 5.1.1 on 2024-12-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_related_exams', '0006_premiumcontent_publisher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premiumcontent',
            name='publisher_id',
        ),
    ]
