# Generated by Django 5.1.1 on 2024-12-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_related_exams', '0007_remove_premiumcontent_publisher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcontent',
            name='publisher_id',
            field=models.IntegerField(default=1),
        ),
    ]
