# Generated by Django 5.1.1 on 2024-12-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_related_exams', '0008_premiumcontent_publisher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumcontent',
            name='Class',
            field=models.CharField(choices=[('12', 'exam'), ('9', 'note')], default='12', max_length=2),
        ),
    ]
