# Generated by Django 5.1.1 on 2025-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_related_exams', '0009_premiumcontent_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='doneexams',
            name='publisher_name',
            field=models.CharField(blank=True, default='SVI', max_length=127),
        ),
        migrations.AddField(
            model_name='premiumcontent',
            name='publisher_name',
            field=models.CharField(blank=True, default='SVI', max_length=127),
        ),
    ]
