# Generated by Django 5.2.5 on 2025-08-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_related_exams', '0010_doneexams_publisher_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doneexams',
            options={'ordering': ['-date_of_application']},
        ),
    ]
