# Generated by Django 5.2.5 on 2025-08-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_profile_teacher_class'),
        ('student_related_exams', '0011_alter_doneexams_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doneexams',
            name='date_of_application',
            field=models.DateField(auto_now_add=True, help_text='Date when the student took this exam'),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='exam_id',
            field=models.CharField(help_text='Unique identifier for the exam (same as package ID)', max_length=50),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='exam_name',
            field=models.CharField(help_text='Name or title of the exam', max_length=100),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='price',
            field=models.IntegerField(default=0, help_text='Price of the exam'),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='publisher_id',
            field=models.IntegerField(default=1, help_text='ID of the teacher who published this exam'),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='publisher_name',
            field=models.CharField(blank=True, default='SVI', help_text='Name of the teacher who published this exam', max_length=127),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='result',
            field=models.DecimalField(decimal_places=2, help_text="Student's result/score on this exam", max_digits=5),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='student',
            field=models.ForeignKey(help_text='Reference to the student who completed this exam', on_delete=django.db.models.deletion.CASCADE, to='profiles.profile_student'),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='subject_name',
            field=models.CharField(help_text='Name of the subject for this exam', max_length=25),
        ),
        migrations.AlterField(
            model_name='doneexams',
            name='time_taken',
            field=models.TimeField(blank=True, default='00:00:00', help_text='Time taken by the student to complete this exam'),
        ),
        migrations.DeleteModel(
            name='PremiumContent',
        ),
    ]
